# Generated by Django 6.0.7 on 2026-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Annul interest rate as a decimal (e.g 0.0150 for 1.5%)",
                max_digits=5,
                verbose_name="Interest Rate",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="kyc_submitted",
            field=models.BooleanField(default=False, verbose_name="KYC Submitted"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("interest", "Interest"),
                ],
                default="transfer",
                verbose_name="Transaction Type",
            ),
        ),
    ]
