# Generated by Django 5.2 on 2025-04-19 20:20

import core_apps.user_auth.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "security_question",
                    models.CharField(
                        choices=[
                            ("grand_father_name", "What is your Grand Father Name"),
                            ("favor_color", "What is your favor color"),
                            ("birth_city", "What is your birth city"),
                            ("child_friends", "What is your child friends name"),
                        ],
                        max_length=50,
                        verbose_name="Security Question",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "ID_NUMBER",
                    models.PositiveIntegerField(unique=True, verbose_name="ID Number"),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("active", "Active"), ("locked", "Locked")],
                        default="active",
                        max_length=50,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("account_execute", "Account Execute"),
                            ("teller", "Teller"),
                            ("branch_manager", "Branch Manager"),
                        ],
                        default="customer",
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                ("failed_login_attempts", models.PositiveSmallIntegerField()),
                (
                    "last_failed_login_attempts",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("otp", models.CharField(blank=True, max_length=6, verbose_name="OTP")),
                (
                    "otp_expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP Expiry Date"
                    ),
                ),
                (
                    "security_answer",
                    models.CharField(max_length=50, verbose_name="Security Answer"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", core_apps.user_auth.managers.UserManager()),
            ],
        ),
    ]
