# Generated by Django 5.2 on 2025-04-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ID_NUMBER",
            field=models.PositiveBigIntegerField(unique=True, verbose_name="ID Number"),
        ),
    ]
