# Generated by Django 5.2 on 2025-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_user_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
