# Generated by Django 6.0.7 on 2026-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcard",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
