# Generated by Django 6.0.7 on 2026-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("toman", "Toman"),
                    ("euro", "Euro"),
                ],
                default="toman",
                max_length=20,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("saving", "Saving")],
                default="saving",
                max_length=20,
                null=True,
                verbose_name="Currency",
            ),
        ),
    ]
