# Generated by Django 6.0.7 on 2026-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_account_currency_profile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
